name: Swift

on: [push]

jobs:
  build:
    name: Swift on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: swift-actions/setup-swift@v2
        if: startsWith(matrix.os, 'ubuntu')
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
        if: startsWith(matrix.os, 'macos')
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libjemalloc-dev
        if: startsWith(matrix.os, 'ubuntu')
      - name: Resolve Swift package dependencies
        run: swift package resolve
      - name: Build
        run: make build
      - name: Run tests
        run: swift test
